### PR TITLE
Release 4.20.2

### PR DESCRIPTION
**Pull request by HeinousGames**

### CODE REVIEW

**Comment by wbaumann** [comment]
I think one of your branches is out of date here. Seeing lots of conflicts

**Comment by wbaumann** [comment]
Ah nevermind - see the new commits 👍

**Comment by HeinousGames** [comment]
I needed to pull in the master branch to resolve conflicts... but now master matches the release branch.... Maybe I shouldn't have pushed directly back to that branch?

**Comment by wbaumann** [comment]
Are these commits on master already?

Also in general - make sure you're always starting your work from the latest `master` commits, since that'll make things easier

**Comment by HeinousGames** [comment]
I understand that Will, but I think I still messed this up. I ended up working directly off of the release branch instead of making a copy of it, so when I merged master into the release branch to resolve conflicts, I actually updated the release branch to match master... is there a way to revert it?

**Comment by wbaumann** [comment]
Sorry to make sure that I understand, were you directly pushing your changes to `release_4.20.2`? And now you want to merge these back to `master`?

Or what's the current state?

**Comment by HeinousGames** [comment]
@wbaumann Yes, I pushed the circleci fixes straight to the release_4.20.2 branch so they wouldn't have to be cherry picked over. But then I merged the master branch to it to resolve the conflicts... forgetting that I was already in the direct branch.

**Comment by wbaumann** [comment]
Do you remember the changes? Let's just open a new MR for master as a
separate commit and ignore the release branch

**Comment by HeinousGames** [comment]
- https://github.com/wbaumann/SmartReceiptsLibrary/pull/197/commits/92bbefd078761658a8eb4726e17161bfd2f60630

- https://github.com/wbaumann/SmartReceiptsLibrary/pull/197/commits/b0515a555f96b8ea9fffd2c3a75513da2558881f

**Comment by wbaumann** [comment]
Are you comfortable just cherry-picking these into another branch, from where we can merge to `master`? Also - did you already push the `master` merge into the release branch?

**Comment by HeinousGames** [comment]
Two days ago this commit was pushed, so yes, I do believe I already pushed the master merge into the release branch: https://github.com/wbaumann/SmartReceiptsLibrary/pull/197/commits/d0c70efce7f07f24705cd2ecf29f709ada5aa81c

Anything special involved in making a new branch, or is it the same as opening a PR from my fork?

**Comment by wbaumann** [comment]
Nope - that's it exactly. New branch with the same code. You can
cherry-pick the specific commits over if you're familiar with that as well!

**Comment by HeinousGames** [comment]
@wbaumann 
I opened a new PR called release_4.20.2_dupe and mentioned the specific commit that had the files that were supposed to be added to master. It is also up-to-date with master so it doesn't accurately reflect what is out in production. You said you just want to ignore the original and dupe release branches?

**Comment by wbaumann** [comment]
@HeinousGames - This one is safe to close, right? I think we already merged this in

**Pull request closed without merging**
