### PR TITLE
Hebrew translations

### PR DESCRIPTION
**Pull request by tomgs**
Hiya,

Will - as per our e-mail conversation, first part of the Hebrew translation's here.

Will work on it bit by bit until it's done:)

Should I translate the two preferences files as well?

### CODE REVIEW

**Comment by wbaumann** [comment]
@tomgs Thank you so much :). All looks great!

If possible, adding in the `preference_defaults.xml` and `preferences.xml files` would be super helpful, since they control what appears in the actual settings menu. 

I'm going to hold off on merging things in for the moment until you've done it all, but let me know if you're tired to doing the translations. I'll merge in your current efforts if so! Thanks!

**Comment by tomgs** [comment]
Hey @wbaumann,

I'll add the preferences files as well as I go along.

Will let you know here when I'm done!

**Comment by wbaumann** [comment]
Sounds great. Thanks!

**Comment by wbaumann** [comment]
Hey @tomgs ,

I hadn't heard from you in some time. I was curious if you were still interested in translating the `preferences.xml` file? No worries if not, as I greatly appreciate the work you've already done (and will merge it in). And no rush of course, just wanted to check if I should merge in your changes as they are.

Thanks!

**Comment by tomgs** [comment]
hey @wbaumann,

Thanks for reaching out!

Just hopped on my finals wagon last week and it's burning all my time:)

I totally haven't forgot and will get to the `preferences` files once I'm done with the exams.

It's up to you whether to merge now or not - I'll get to them, I imagine, by the end of August at the latest. 

Maybe it'll be a good idea to merge, actually, so we can see the indentation live? Check to see it's working properly?

Thanks!

Tom

**Comment by wbaumann** [comment]
@tomgs Sure thing. I'll merge it in as is now, and we can get to the `preferences` whenever you're free up.

Thanks for all your help! And good luck with your finals :)

**Comment by tomgs** [comment]
Thanks! WIll it be live on the official app as while?

I mean - can I just update the app through play store and the locale values
will be pushed?

**Comment by wbaumann** [comment]
@tomgs I'll include it with the next update, but it'll probably take ~2 weeks or so. If you want, though, I can build it all for you right now to test out? Let me know!

**Comment by tomgs** [comment]
Would be really happy, thanks!

If the indentation's off, I'll need to re-do the entire strings file again.
Would be happy to get some visual input so I could run this maybe even
today and give back feedback.

**Comment by wbaumann** [comment]
@tomgs Put together a build to test here:

* https://www.dropbox.com/s/x53tf6nk704t6xz/app-free-release_hebrew-1.apk?dl=0

Let me know what you think. I had to make a few slight modifications to get the build working properly:

* https://github.com/wbaumann/SmartReceiptsLibrary/commit/b044226dd07c9779fc5cc40852eaff521be98a1b

One more reason to finish getting my CI tools in order. Thanks!

**Comment by tomgs** [comment]
Will take a look at it in the next hour or so and let you know what I think.
Thanks!

**Comment by wbaumann** [comment]
No rush of course. Take care of the finals and whatnot first :)

**Comment by tomgs** [comment]
Just installed the build and changed the language of my device to Hebrew (I
use English usually) - no cigar, still seeing the English everywhere.
Thoughts?

**Comment by wbaumann** [comment]
Interesting - looks like Android uses both `values-he` and `values-iw` for the Hebrew translations:

https://stackoverflow.com/questions/8393771/android-not-using-finding-my-hebrew-localization

I'll look into a good way to manage this

**Comment by wbaumann** [comment]
New version, now with all files in the `values-iw` folder. Seems like `values-he` is only used on legacy systems, so I'm not bothering with a symlink between the two for now

**Comment by tomgs** [comment]
Haven't forgot, let me get on it later tonight and see how things go.
Thanks!

**Comment by wbaumann** [comment]
@tomgs No worries! Take your time

**Comment by tomgs** [comment]
The link is dead tho... @wbaumann

**Comment by wbaumann** [comment]
My fault. Forgot to change the link:

https://www.dropbox.com/s/upavcyxagf9wlem/app-free-release_hebrew-2.apk?dl=0

Let me know if that one works

**Comment by wbaumann** [comment]
Nice looks good :)

I'll do some tests on an emulator as well to check if there are any other issues with the right-to-left layouts

**Pull request merged**
